### ISSUE TITLE
Bugs: at creating a society with wrong number of characeter, bad display

### ISSUE THREAD

**Issue by Duning5** [mc-societies/societies#1]
I've found a bug when creating a society, instead of displaying the number of characters needed, it displays "{0}". For exaple: The Tag needs at least {0} characters more.

**Comment by Duning5** [comment]
/societies home set doesn't work with spanish translation.

**Comment by maxammann** [comment]
Marked for next version :D

**Comment by maxammann** [comment]
Fixed in https://github.com/mc-societies/societies/commit/047e8cdeef66c33d159cc2c7cc8905f3b1db9905
